version: "3.7"

services:
  api:
    container_name: ittemita-api
    build: .
    command: bash -c "python wait-for-postgres.py && python manage.py runserver 0.0.0.0:8000 && python manage.py migrate"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    env_file: .env
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "./.data:/var/lib/postgresql/data"
